import { useNavigate } from 'react-router-dom'
import { useApp } from '../App'
import MetricCard from '../components/MetricCard'
import Sparkline from '../components/Sparkline'

export default function BacktestResults() {
  const navigate = useNavigate()
  const { strategy, backtestResults, backtestError } = useApp()

  if (backtestError) {
    return (
      <div className="page-stack">
        <div className="page-heading">
          <div><div className="eyebrow">Step 3 of 3</div><h1>Backtest Failed</h1></div>
          <button className="button secondary" onClick={() => navigate('/strategy')}>← Edit Strategy</button>
        </div>
        <div className="panel">
          <div className="section-title"><h2>Error Details</h2></div>
          <p style={{ color: '#b91c1c', fontWeight: 'bold' }}>LEAN Engine encountered an error:</p>
          <pre style={{ background: '#f8fafc', padding: '16px', borderRadius: '8px', overflowX: 'auto', fontSize: '12px', border: '1px solid #fca5a5' }}>
            {backtestError}
          </pre>
          {backtestResults?.leanLogs && (
            <>
              <h3 style={{ marginTop: '20px' }}>Full LEAN Logs</h3>
              <pre style={{ background: '#1e1e1e', color: '#d4d4d4', padding: '16px', borderRadius: '8px', overflowX: 'auto', fontSize: '11px', height: '300px', overflowY: 'auto' }}>
                {backtestResults.leanLogs}
              </pre>
            </>
          )}
        </div>
      </div>
    )
  }

  if (!backtestResults) {
    return (
      <div className="page-stack">
        <div className="page-heading">
          <div><div className="eyebrow">Step 3 of 3</div><h1>No Results Yet</h1></div>
          <button className="button primary" onClick={() => navigate('/strategy')}>Run Backtest →</button>
        </div>
      </div>
    )
  }

  const { metrics, equityCurve, trades } = backtestResults

  // Format equity curve for Sparkline
  const formattedCurve = equityCurve?.map(pt => ({
    label: new Date(pt.timestamp * 1000).toLocaleDateString(),
    value: pt.equity
  })) || []

  // Ensure trades exist
  const tradeList = trades || []

  return (
    <div className="page-stack">
      <div className="page-heading">
        <div>
          <div className="eyebrow">Step 3 of 3</div>
          <h1>Backtest Results</h1>
          <p>{strategy.name} · {strategy.asset} · {strategy.startDate} to {strategy.endDate}</p>
        </div>
        <button className="button secondary" onClick={() => navigate('/explore')}>Explore Parameters</button>
      </div>

      <div className="demo-note" style={{ background: '#eaf1ff', borderColor: '#2563eb', color: '#1d4ed8' }}>
        <strong>REAL DATA:</strong> These results are generated by the C# backend and executed historically using the LEAN engine.
      </div>

      <div className="metric-grid">
        <MetricCard label="Return" value={`${metrics?.totalReturn > 0 ? '+' : ''}${metrics?.totalReturn.toFixed(2)}%`} tone={metrics?.totalReturn >= 0 ? "positive" : "negative"} />
        <MetricCard label="Max Drawdown" value={`${metrics?.maxDrawdown.toFixed(2)}%`} tone="negative" />
        <MetricCard label="Total Trades" value={metrics?.totalTrades || 0} />
        <MetricCard label="Win Rate" value={`${metrics?.winRate.toFixed(2)}%`} />
      </div>

      <section className="panel">
        <div className="section-title">
          <div>
            <h2>Equity Curve</h2>
            <span className="muted">Actual Portfolio Value (Start: ₹{metrics?.startEquity.toLocaleString()})</span>
          </div>
        </div>
        {formattedCurve.length > 0 ? (
           <Sparkline data={formattedCurve} />
        ) : (
           <p className="muted" style={{ padding: '40px', textAlign: 'center' }}>No equity data available.</p>
        )}
      </section>

      <div className="two-col">
        <section className="panel">
          <div className="section-title"><h2>Drawdown</h2><span className="muted">Peak-to-trough risk</span></div>
          <div className="drawdown-box">
            <div className="drawdown-fill" style={{ height: `${Math.min(100, Math.abs(metrics?.maxDrawdown || 0) * 2.6)}%` }} />
            <span>{metrics?.maxDrawdown.toFixed(2)}% max</span>
          </div>
        </section>

        <section className="panel">
          <div className="section-title"><h2>Recent Trades</h2><button className="text-button" onClick={() => { document.getElementById('trades').scrollIntoView(); }}>View All</button></div>
          <div className="mini-list">
            {tradeList.length === 0 && <p className="muted">No trades executed.</p>}
            {tradeList.slice(-5).reverse().map((t) => (
              <div className="mini-row" key={t.orderId}>
                <span>{new Date(t.time).toLocaleDateString()}</span>
                <strong className={t.direction === 'Buy' ? 'buy-text' : 'sell-text'}>{t.direction}</strong>
                <span>₹{t.price.toLocaleString()}</span>
              </div>
            ))}
          </div>
        </section>
      </div>

      <div id="trades" className="panel">
        <div className="section-title"><h2>All Trades</h2></div>
        <div className="table-wrap">
          {tradeList.length > 0 ? (
            <table>
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Date</th>
                  <th>Action</th>
                  <th>Price</th>
                  <th>Quantity</th>
                </tr>
              </thead>
              <tbody>
                {tradeList.map((t) => (
                  <tr key={t.orderId}>
                    <td>{t.orderId}</td>
                    <td>{new Date(t.time).toLocaleString()}</td>
                    <td><span className={t.direction === 'Buy' ? 'buy-text' : 'sell-text'}>{t.direction}</span></td>
                    <td>₹{t.price.toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                    <td>{t.quantity}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <p className="muted">No trade history to display.</p>
          )}
        </div>
      </div>

      <div className="bottom-actions">
        <button className="button secondary" onClick={() => navigate('/parameters')}>← Change Parameters</button>
        <button className="button primary" onClick={() => navigate('/compare')}>Compare Strategies →</button>
      </div>
    </div>
  )
}
